# Site Settings
theme: jekyll-theme-minimal
title: Confox's Homepage
description: Bookmark this page to stay updated on my latest projects, developments, and tech explorations!
url: "https://your-github-username.github.io" # Replace with your GitHub Pages URL
baseurl: "" # For custom domain use, specify "/sub-directory" if your site is hosted in one

# SEO and Social Meta Tags
author: Confox
email: your-email@example.com # Replace with your email address
social_links:
  github: https://github.com/confox
  twitter: https://twitter.com/your_twitter_handle # Add your Twitter handle if applicable
  linkedin: https://linkedin.com/in/your_linkedin_profile # Add LinkedIn if applicable

# Social Sharing
twitter_username: your_twitter_handle # Add your Twitter handle here if you want Twitter card integration
github_username: confox # Your GitHub username
show_excerpts: true # Option to show excerpts in listings

# Appearance
paginate: 5 # Number of posts to show per page (if blogging)
highlighter: rouge # Syntax highlighting for code

# Optional Plugins
plugins:
  - jekyll-feed # RSS feed for blog updates
  - jekyll-sitemap # Generates a sitemap for better search engine indexing
  - jekyll-seo-tag # Adds meta tags for SEO
  - jekyll-paginate # Pagination support

# Markdown Options
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    inline_theme: base16.light
    line_numbers: true

# Build Settings
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
